# Generated by Django 3.2.7 on 2021-09-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='my_users',
        ),
    ]
